language: elm
elm:
  - elm0.19.0

cache:
  directories:
    - elm-stuff/build-artifacts
    - elm-stuff/packages
    - tests/elm-stuff/build-artifacts
    - test/elm-stuff/packages

script:
  - elm-test
